name: Get Subscription Weekly

on:
  schedule:
    - cron: '50 23 * * *'
    # - cron: '* 05 * * *'
    - cron: '12 11 * * *'
    # - cron: '14 14 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install tqdm
      run: |
        pip install tqdm

    - name: Collect Subscribe
      id: collect
      run: |
        cd subscribe
        python -u collect.py -s
      continue-on-error: true

    - name: Output directory structure
      run: |
        cd ./data
        ls -R

    - name: Send success notification # 成功时发送通知
      if: success()
      env:
        WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
      run: |
        curl -X POST "https://wxpusher.zjiecode.com/api/send/message" -H "Content-Type: application/json" -d '{
          "appToken":"'"$WXPUSHER_APPTOKEN"'",
          "content":"机场爬虫运行成功",
          "contentType":1,
          "topicIds":[30318],
          "verifyPay":false, 
          "verifyPayType":0
        }'
      
    - name: Send failure notification # 失败时发送通知
      if: failure()
      env:
        WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
      run: |
        curl -X POST "https://wxpusher.zjiecode.com/api/send/message" -H "Content-Type: application/json" -d '{
          "appToken":"'"$WXPUSHER_APPTOKEN"'",
          "content":"机场爬虫运行失败",
          "contentType":1,
          "topicIds":[30318],
          "verifyPay":false, 
          "verifyPayType":0
        }'
        
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT}}
      run: |
        cd ./data
        gh gist edit ${{ secrets.GIST_ID }} --add "clash.yaml"
        gh gist edit ${{ secrets.GIST_ID }} --add "subscribes.txt"
        gh gist edit ${{ secrets.GIST_ID }} --add "domains.txt"
        gh gist edit ${{ secrets.GIST_ID }} --add "valid-domains.txt"

    - name: Configure git
      run: |
        git config --global user.email "${{ secrets.EMAIL }}" # 使用您的 GitHub 邮箱地址
        git config --global user.name "${{ secrets.NAME }}" # 使用您的 GitHub 用户名

    - name: Commit and Push
      run: |
       cd ./data # 根据需要进入到文件所在目录
       git add clash.yaml
       git commit -m "Update clash.yaml" # 提交信息根据需要自定义
       git push
